services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8889 -b '0.0.0.0'"
    volumes:
      - .:/app
      - app_bundle:/usr/local/bundle
    ports:
      - '8889:8889'
    networks:
      - default
      - op_network
    tty: true

volumes:
  app_bundle:

networks:
  default:
  op_network:
    external: true
    name: ruby-postgres-docker-templete_default
